---
dependency:
  name: gilt
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance-1
    image: arm32v7/debian
provisioner:
  name: ansible
  lint: |
  set -e
  yamllint .
  ansible-lint
scenario:
  name: {{ cookiecutter.scenario_name }}
verifier:
  name: testinfra
  lint: |
  set -e
  yamllint .
  ansible-lint
